### ISSUE TITLE
Error rejecting Domestic Payment Consent

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#1015]
The UI displays an error saying "Bad Request" when rejecting a Domestic Payment Consent.

Nothing is logged in the RCS to indicate what the issue is.

In the IG logs we see:
```
{
"Code": "BAD_REQUEST",
"Id": "8427891f-daea-405c-9776-3469d6a4f014",
"Message": "Bad Request",
"Errors": [
    {
        "ErrorCode": "OBRI.RCS.consent.decision.Invalid",
        "Message": "Invalid remote consent decision token. Invalid format"
    }
}
```

**TO DO Test other consent types**

**Comment by jorgesanchezperez** [comment]
When the consent is rejected by the `PSU` user, currently the debtorAccount value is `""` if the user have not select any account when rejects the consent.
**Example decision submitted**
```json
{
    "consentJwt": "eyJ0eXAiOiJKV1QiL....",
    "decision": "Rejected",
    "debtorAccount": ""
}
```
 in the RCS backend the jackson mapper deserialize the json payload submitted from RCS-UI including empty properties, and fails because the property `debtorAccount` defined in the object `ConsentDecisionDeserialized` is defined as  `FRFinancialAccount` type, jackson try to deserialize it as String raising an exception.

To prevent that issue and never submit the debtorAccount as `""` (empty string) the UI consents submit event has been modified for all payments to set the debtorAccount always as `null` when the consent is rejected by the user.
The debtorAccount can be ignore when the consent is rejected, the consent no needs to be patched with the accountId selected by the user when the consent is rejected.

```json
{
    "consentJwt": "eyJ0eXAiOiJKV1QiL....",
    "decision": "Rejected",
    "debtorAccount": null
}
```
So that the property `debtorAccount` will be ignored by jackson when deserialize the payload.
