### ISSUE TITLE
Remove developer kustomize overlays from the gateway project. 

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#302]
This is confusing for customers, and it leads customers to believe they will need to create an overlay in that repository in order to be able to deploy IG.

Investigate how we can have a separate repository (possibly private) for our own overlays and kustomizations.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/302?planning-poker) with ZenHub @andra-racovita @BohoCode @dbadham-fr @frlaura-jianu @mariantiris

**Comment by shaunharrisonFR** [comment]
Issue I'm having is as follows

We use the config map values in the gateway repo [kustomizeConfig](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/tree/master/kustomize/base/kustomizeConfig) as variables, so that when we set the [ingress rules ](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/master/kustomize/base/7.1.0/ingress/ingress.yaml#L22) the value isn't hardcoded and is different for each environment (obdemo.bohocode.forgerock.financial & obdemo.shaunharrisonfr.forgerock.financial)

When the configmap is being created as part of the IG there is no issues (although maybe there should be) as what we're saying is, generate new configmap in the [kustomizeConfig](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/master/kustomize/base/kustomizeConfig/kustomization.yaml#L9) file, but we are also creating the configfile with the same name in the [overlay](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/master/kustomize/overlay/7.1.0/securebanking/bohocode/configmap.yaml)

When I've moved the configmap into its own repo , issues start to appear, as we are saying that we want to create a new securebanking-platform-config with the [literal values ](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/master/kustomize/base/kustomizeConfig/kustomization.yaml#L14) but our config map has loads of different values, so argocd will want to constantly sync the configmap over and over switching between the full configmap and the 4 values in the literal. 

To get around this, I've tried referencing the new configmap repo as a [resource](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/302-remove-kustomize-from-gateway-repo/kustomize/base/kustomizeConfig/kustomization.yaml#L6), annoyingly this means hardcoding to my overlay, so isn't really an option. But what this does is keep the config maps in line, the only issue then is that the argocd.argoproj.io/instance value is different for the configmap as again it thinks the configmap is being created within the IG when it already exists in the configmap repo, so it does still sync over and over , but none of the values change this time as before

**Comment by shaunharrisonFR** [comment]
Code all merged, put into review while we wait and make sure envs are still working as expected
