### ISSUE TITLE
Fix test for Read Refund

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#492]
Some tests related with Read Refund are currently disabled, there is a comment stating:

`//TODO: Waiting for the fix from the issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/241`

https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/241 has been fixed.

I've tried running the test but we hit a NPE due to paymentResult.data.refund being null on the following line:
```java
assertThat(paymentResult.data.refund.account.identification).isEqualTo(consent.data.initiation.debtorAccount.identification)
```
> Probably Will be necessary review all Get payments by consentId.

**Comment by jorgesanchezperez** [comment]
## Reason
The ApiOperation getDomesticPaymentsPaymentId expects the below header:
 - x-read-refund-account: value `Yes` or `No` to specifies to share the refund account details with PISP, the value needs to be obtained from the consent from the field `ReadRefundAccount`.
But never arrives because IG never set up that header, currently is always evaluated as `null` so then the `refund` never is fill with the `debtorAccount` data.

## Source references
- [uk-gateway domestic payment access route](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/master/config/7.1.0/securebanking/ig/routes/routes-service/33-ob-domestic-payments-access.json)
- [rs getDomesticPaymentsDomesticPaymentId](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/blob/e7b6b19fe8ab1e3bb2f18349747eadb740274452/securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment/v3_1_5/domesticpayments/DomesticPaymentsApiController.java#L112)

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/492?planning-poker) with Zenhub @frlaura-jianu @mariantiris
