### ISSUE TITLE
Publish postman collections and documentation ob-sandbox-v1

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#712]
As we use Postman for test purposes we need:
- [x] Publish postman collections for customers
- [x] Publish postman environments for customers
- [x] Add documentation to the postman collection
- [x] Export the collection and store it with the release
- [x] Export an environment for ob-sandbox-v1 and make it available to customers [here](https://github.com/SecureApiGateway/secure-api-gateway-releases)

**Comment by BohoCode** [comment]
I have created two postman collections called 
Secure API Gateway v1.0.0 - Open Banking UK TPP flows (OBIE Certificates), and
Secure API Gateway v1.0.0 - Open Banking UK TPP flows (Test Certificates)

It seems wrong to have to maintain two collections. There have historically been two collections due to the differences in how we handle signing certificates issued by OB and by IG. 

There is no way to easily obtain the signing key from the IG (Test Certificates). There is a convenience method to obtain the pem/key pair for the TLS (transport) keys, but not for the Signing Key. Rather than do the signing in the postman collections (the client), the Test Certificates collection instead makes a request to IG and asks IG to sign the payload. This is seen for example every time we need to create a client_credentials jwt. 

We could unify the two collections if we could add a convenience method to IG to obtain the key/pem pair for the IG test certificates. The signing key could then be added as a postman variable in the same way is it would be added of the OBIE Certificates collection. 

This would mean we could have one Postman collection, with two different sections for creating the registration request. One that uses OB Certs and one that uses IG issues certs, and the rest of the collection would work which ever type of certs you were using.

**Comment by BohoCode** [comment]
The above improvement is addressed here;
https://github.com/secureapigateway/secureapigateway/issues/945

**Comment by jorgesanchezperez** [comment]
Exported Postman collection: `Secure API Gateway v1.0 - Open Banking UK TPP Flows.postman_collection.json`
Exported v1.0.0 cluster environment: `v1.0.0 release cluster.postman_environment.json`
The postman collection and environment descriptors, to be imported into postman application lives in the repository: https://github.com/SecureApiGateway/secure-api-gateway-releases in the `postman` folder
