### ISSUE TITLE
Enable tag protection across all of our git repos

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#891]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules

**Comment by shaunharrisonFR** [comment]
@BohoCode @jorgesanchezperez Just to confirm, are we using v1.0.0 as the tag or 1.0.0?

**Comment by shaunharrisonFR** [comment]
Issue with github actions creating branches and tags when enabled, will review for V2

**Comment by shaunharrisonFR** [comment]
This is now done via rulesets (old tag protection rules are being sunsetted) 

Create, Update (including force) and deletion restrictions are in place for all used repos in SAPIG

Release team have an bypass to these rules as we do with our branch protection so that our release process can do what is needed
