### ISSUE TITLE
Submitting valid File Payment results in "OBRI.Payment.Invalid" error

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#981]
Version: 1.0.1
Fixed In: 1.0.2

## Description
When submitting a File Payment a 400 (Bad Request) error is received with the following body;

```
{
    "Code": "400",
    "Id": "15c24eeed658708baf6e3969e12450b9",
    "Message": "[Status: 400 Bad Request]",
    "Errors": [
        {
            "ErrorCode": "OBRI.Payment.Invalid",
            "Message": "Payment invalid. Payment initiation received doesn't match the initial payment request: 'The initiation field from payment submitted does not match with the initiation field submitted for the consent'"
        }
    ]
}
```

## Steps to Reproduce
1. Perform DCR
2. Create a File Payment (JSON) Consent
3. Use hybrid flow to give user consent
4. Use authorization_code grant to obtain access token with consent
5. Submit File Payment
### Expected Behaviour
The payment is accepted and a 201 (Created) is returned.
### Actual Behaviour
The payment is rejected with the error provided in the Description section.

**Comment by jorgesanchezperez** [comment]
To verify the equality between the `Initiation file payment submission` section against the `initiation file payment consent` section fails because the equality between `ControlSum` value is false.

To make the equality verification is used the equals method implemented in the Initiation class type, where is used `Objects.equals(ob1, ob2)` where each type calls his own equals implementation.

The property that fails the equality verification is `ControlSum` where the type is BigDecimal.

**BigDecimal#equals**

This method considers two BigDecimal objects equal only if they are equal in value and scale. 
Therefore 2.0 is not equal to 2.00 when compared by this method since the former has [BigInteger, scale] components equal to [20, 1] while the latter has components equal to [200, 2].

## Debugging
**File payment consent submitted**
```json
{
  "Data": {
    "Initiation": {
      "FileType": "UK.OBIE.PaymentInitiation.3.1",
      "FileHash": "b5OLwRye50tF1mVouNRR+4Mh8uhZKddKiMwT3N8nSlU=",
      "FileReference": "JsonExample",
      "NumberOfTransactions": "4",
      "ControlSum": 87.00,
      "RequestedExecutionDateTime": "2023-09-27T13:03:06+00:00",
      "RemittanceInformation": {
        "Reference": "FRESCO-101",
        "Unstructured": "Internal ops code 5120101"
      }
    }
  }
}
```
>"ControlSum": 87.00

**File payment consent deserialised from IDM**
```java
class OBWriteFile2DataInitiation {
    fileType: UK.OBIE.PaymentInitiation.3.1
    fileHash: b5OLwRye50tF1mVouNRR+4Mh8uhZKddKiMwT3N8nSlU=
    fileReference: JsonExample
    numberOfTransactions: 4
    controlSum: 87.0
    requestedExecutionDateTime: 2023-09-27T13:03:06.000Z
    localInstrument: null
    debtorAccount: null
    remittanceInformation: class OBWriteDomestic2DataInitiationRemittanceInformation {
        unstructured: Internal ops code 5120101
        reference: FRESCO-101
    }
    supplementaryData: null
}
```
> controlSum: 87.0

**File payment submission**
```java
class OBWriteFile2DataInitiation {
    fileType: UK.OBIE.PaymentInitiation.3.1
    fileHash: b5OLwRye50tF1mVouNRR+4Mh8uhZKddKiMwT3N8nSlU=
    fileReference: JsonExample
    numberOfTransactions: 4
    controlSum: 87.00
    requestedExecutionDateTime: 2023-09-27T13:03:06.000Z
    localInstrument: null
    debtorAccount: null
    remittanceInformation: class OBWriteDomestic2DataInitiationRemittanceInformation {
        unstructured: Internal ops code 5120101
        reference: FRESCO-101
    }
    supplementaryData: null
}
```
> controlSum: 87.00

**Equality between submission and consent**
| property | result |
|---|---|
|fileType | true |
|fileHash | true |
|fileReference | true |
|numberOfTransactions | true |
|controlSum | false |
|requestedExecutionDateTime | true |
|localInstrument | true |
|debtorAccount | true |
|remittanceInformation | true |
|supplementaryData | true |

**controlSum: false**
Comparison: controlSum: 87.00 (payment submission) vs controlSum: 87.0 (stored payment consent)
| Property | submission initiation.controlSum | Stored consent initiation.controlSum |
|---|---|---|
|scale| 2 | 1 |
|precision| 4 | 3 |
|unscaledValue| 8700 | 870 |
|doubleValue| 87.0 | 87.0 |
|intValueExact| 87 | 87 |

It seems that in the process of deserialization and serialization is lost precision and scale.

**Comment by jorgesanchezperez** [comment]
After a discussion about how to fix propertly the issue with the deserialization in IG.

As we use `entity.getJson()` to set the entity in a new request to call the Backend service the entity is serialize/deserialize using jackson ObjectMapper with a simple custom configuration, where the result of the entity may differs from the original request entity.

We decided that the entity from the request needs to keep exactly the same data sent by the TPP in the original request and we need to build the requests to call the Backends with the entity as String instead of as Json, so that the entity will remain exactly with the same data sent by the TPP.

**Solution**
Update all groovy scripts in IG to use String instead of Json when a new request is built to call any backend and when a response is built to be sent to the TPP.

**Comment by BohoCode** [comment]
Nice. 

On a broader point, we should **not** be modifying and request or response payloads in IG on the way too or back from the RS. We should be able to guarantee to customers that what they receive from the ApiClient, or what they return to the ApiClient has not been changed.

**Comment by jorgesanchezperez** [comment]
Although IG sends the payload just as the TPP has sent it.
The issue with numbers persist, idm deserialize the payload and the zeros  are trimmed.

**Examples**

| TPP submits | IG payload request to IDM | IDM deserialise it and stored | IMD payload response to IG|
|---|---|---|---|
| 0.0 | 0.0 | 0 | 0.0 |
| 85.00 | 85.00 | 85 | 85.0 |
| 85.050 | 85.050 | 85.05 | 85.05 |
| 87.06080 | 87.06080 | 87.0608 | 87.0608 |
| 87.0608000 | 87.0608000 | 87.0608 | 87.0608 |
